export const PLAYLISTS_IS_SHOWING = 'PLAYLISTS_IS_SHOWING';
export const MIXES_IS_SHOWING = 'MIXES_IS_SHOWING';
export const MIX_TOGGLE_CREATE = 'MIX_TOGGLE_CREATE';
export const VISUAL_EFFECTS_TOGGLE = 'VISUAL_EFFECTS_TOGGLE';
