export const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING';
export const PLAYLIST_IS_LOADING = 'PLAYLIST_IS_LOADING';
export const PLAYLIST_FETCH_DATA_SUCCESS = 'PLAYLIST_FETCH_DATA_SUCCESS';
export const PLAYLIST_ITEMS_FETCH_DATA_SUCCESS = 'PLAYLIST_ITEMS_FETCH_DATA_SUCCESS';
export const PLAYLIST_ITEMS_FETCH_DATA_SUCCESS_SHUFFLE =
  'PLAYLIST_ITEMS_FETCH_DATA_SUCCESS_SHUFFLE';
export const PLAYLIST_LOAD_ITEMS_DATA = 'PLAYLIST_LOAD_ITEMS_DATA';
export const PLAYLIST_LOAD_DATA = 'PLAYLIST_LOAD_DATA';
export const PLAYLIST_RESET = 'PLAYLIST_RESET';
export const PLAYLIST_REMOVE = 'PLAYLIST_REMOVE';
export const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED';
